---
Name: CodeBank
After: 
    - "framework/*"
    - "cms/*"
---
Member:
    extensions:
        - 'CodeBankMember'

Security:
    extensions:
        - 'CodeBankSecurity'

HighlightedContentField:
    theme: 'Default'